"""Revertir cambios

Revision ID: b1b3308e72a0
Revises: cd4ca0058b79
Create Date: 2026-02-25 20:23:20.498101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1b3308e72a0'
down_revision = 'cd4ca0058b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apaterno', sa.String(length=50), nullable=True))
        batch_op.drop_column('telefono')
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('apaterno')

    # ### end Alembic commands ###
